### ISSUE TITLE
WriteFeaturesMarkFDK: dict Keys() object needs to be converted to list before sorting

### ISSUE THREAD

**Issue by typoman** [adobe-type-tools/python-modules#12]
It's because of the sort method that is used after. See the line:
https://github.com/adobe-type-tools/python-modules/blob/d65dda02678754920abce4a03c92a8e2fe5be22e/WriteFeaturesMarkFDK.py#L524

**Comment by josh-hadley** [comment]
I realize this has already been addressed (and there's no need to make another update), but for later reference I think this could be done more succinctly by replacing these two lines:
```
        anchorGroupList = list(self.anchorsDataInLigaturesDict.keys()) # ['aboveAR,arAlefMaksura_AlefMaksura', 'aboveAR,arAlefMaksura_AlefMaksura.f', 'aboveAR,arAlefMaksura_AlefMaksura.fj',
        anchorGroupList.sort()
```

with this one line:

```
        anchorGroupList = sorted(self.anchorsDataInLigaturesDict)
```

Reason: when `sorted()` is called on a dict, by default it sorts on the dict's keys _and_ returns the result as a `list` – exactly what we want here (and maybe other places in this repo).

Example:
```
>>> d = {'z': '9', 'a': '2', 'b': 4}
>>> d.keys()
dict_keys(['z', 'a', 'b'])
>>> list(d.keys())
['z', 'a', 'b']
>>> sorted(d)
['a', 'b', 'z']
>>> 
```
