### ISSUE TITLE
import roboFont

### ISSUE THREAD

**Issue by typemytype** [adobe-type-tools/python-modules#3]
RoboFont was never supposd to work as module. I guess this was auto generated by py2app.

I would advice to test if a script is running inside RoboFont by:

```Python
try:
    import mojo.roboFont
    inRF = True
except:
    inRF = False
```

this occurs in https://github.com/adobe-type-tools/box-drawing/blob/master/boxDrawing.py#L45 and https://github.com/adobe-type-tools/python-modules/blob/master/WriteFeaturesMarkFDK.py#L117

**Comment by miguelsousa** [comment]
Fixed.
Was also in https://github.com/adobe-type-tools/python-modules/blob/master/WriteFeaturesKernFDK.py#L156
