### ISSUE TITLE
Disperse repository?

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/python-modules#8]
I have an impression the notion of a separate python-modules repo may be somewhat outdated. The only “modules-only” scripts are `AdobeFontlabUtils.py` and `BezChar.py`, which could be moved to the FontLab Scripts repo.
With adding a few lines of code, most other modules could be made into directly-useable scripts (some already are), and then placed into the python-scripts repo.

Thoughts?

**Comment by miguelsousa** [comment]
Sounds good to me. The only thing I'd ask is, migrate all the files to the new locations, make any necessary changes to them, and only then take down this repo.

**Comment by frankrolf** [comment]
After 5 years, this repo feels like a good home for the mark- and kernFeatureWriters. I hope to fold them into the FDK eventually. The other collateral can eventually be (re-)moved, but there’s no high urgency for this.
